title: zburkett.io
email: z@zburkett.io
description: >-
  My personal little corner of the internet.
domain: zburkett.io
baseurl: ""
url: https://zburkett.io

google_analytics: G-3MM50XVYQ3

plugins:
  - jekyll-feed
theme: jekyll-theme-minima

show_excerpts: true
header_pages:
  - blog.md
  - demos.md
  - about.md

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/zacharyburkett" }
    - { platform: twitter, user_url: "https://twitter.com/zburkett" }
    - { platform: rss, user_url: "feed.xml" }

exclude:
  - image-zoo-src
