title: zburkett.io
email: z@zburkett.io
description: >-
  My personal little corner of the internet.
github_username: zacharyburkett
twitter_username: zburkett
rss: rss
domain: zburkett.io
baseurl: ""
url: https://zburkett.io

google_analytics: G-3MM50XVYQ3

plugins:
  - jekyll-feed
theme: minima

show_excerpts: true
header_pages:
  - blog.md
  - demos.md
  - about.md

minima:
  skin: dark

exclude:
  - image-zoo-src
